services:
  postgres:
    image: postgres:latest
    container_name: postgres_bd_produtosapi
    restart: always
    environment:
      POSTGRES_DB: bd_produtosapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: